# Cloudflare Pages configuration
[build]
command = "cd frontend && npm install && npm run build"
publish = "frontend/build"

[build.environment]
NODE_ENV = "production"
REACT_APP_BACKEND_PORT = "443"

# Redirects for SPA routing
[[redirects]]
from = "/api/*"
to = "https://atxp-express-backend.your-subdomain.workers.dev/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200