services:
  - type: web
    name: atxp-express-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_PORT
        value: 3000
      - key: ATXP_CONNECTION_STRING
        sync: false
    healthCheckPath: /api/health

  - type: web
    name: atxp-express-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://atxp-express-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html