services:
  - type: web
    name: atxp-express-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_PORT
        value: 3000
    healthCheckPath: /api/health

  - type: web
    name: atxp-express-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /api/*
        # TODO: Replace 'atxp-express-backend' with your actual backend service name
        # The backend service URL will be: https://YOUR-BACKEND-SERVICE-NAME.onrender.com
        destination: https://atxp-express-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html