services:
  - type: web
    name: atxp-express-app
    runtime: node
    plan: free
    buildCommand: |
      # Build both backend and frontend
      cd backend && npm install && npm run build
      cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health