services:
  - type: web
    name: atxp-express-app
    runtime: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health