# Cloudflare Workers configuration for the backend
name = "atxp-express-backend"
compatibility_date = "2023-10-30"

# Main worker script
main = "backend/worker.ts"

# Environment variables (users will set their own ATXP_CONNECTION_STRING)
[env.production.vars]
NODE_ENV = "production"
FRONTEND_PORT = "3000"