name: Node.js Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'  # Added this line

    - name: Install dependencies
      run: npm ci

    - name: Install backend dependencies  
      run: cd backend && npm ci

    - name: Run build
      run: npm run build
      
